### ISSUE TITLE
Twitter handle no funciona correctamente

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#57]
Cuando se adiciona el twitter handle en un post la compilación revienta

Build Failure :'(

Building of the artifact “blog/first-post/index.html” failed. This is what we know about the problem:

```
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 797, in update
    yield ctx
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1042, in build_artifact
    build_func(artifact)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/build_programs.py", line 183, in build_artifact
    self.source['_template'], this=self.source)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 652, in render_template_into
    this=this, **extra)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/environment.py", line 517, in render_template
    return self.jinja_env.get_or_select_template(name).render(ctx)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/Extended/frontend/Proyectos/scot3004/django-quilla-web/templates/blog-post.html", line 2, in top-level template code
    {% from "macros/blog.html" import render_blog_post %}
  File "/Volumes/Extended/frontend/Proyectos/scot3004/django-quilla-web/templates/layout.html", line 55, in top-level template code
    {% block body %}{% endblock %}
  File "/Volumes/Extended/frontend/Proyectos/scot3004/django-quilla-web/templates/blog-post.html", line 17, in block "body"
    <a href="https://twitter.com/{{ post.twitter_handle}}">
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'post' is undefined
```

**Comment by Scot3004** [comment]
Resuelto #58
